### ISSUE TITLE
Missing startup and linker for STM32WBA6x

### ISSUE THREAD

**Issue by xanthio** [STMicroelectronics/cmsis-device-wba#1]
Devices STM32WBA62, STM32WBA63, STM32WBA64 and STM32WBA65 are active on st.com product page but not yet supported by CMSIS due to the lack of startup and linker scripts.

**Comment by KRASTM** [comment]
Hello @xanthio,

Thank you for the report.

Indeed, the devices you mentioned are active and launched by ST, but they are not yet supported in the latest official release version 1.5.0 (`as already mentioned in the release note: Official Release of STM32CubeWBA Firmware package supporting STM32WBA50xx, STM32WBA52xx, STM32WBA54xx, STM32WBA5Mxx, and STM32WBA55xx devices`) or by CMSIS. They will be available in a future release.

Please, allow me to close this issue, thank you for your comprehension.

With regards
